server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # not register self
    fetchRegistry: false  # not to find server
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/